import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"
import { FirebaseClientProvider } from '@/firebase/client-provider';
import { CharacterProvider } from '@/context/CharacterContext';
import { Poppins, Inter } from 'next/font/google'
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'PersonaCraft AI',
  description: 'Generated by Firebase Studio',
};

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['400', '600', '700']
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("dark", poppins.variable, inter.variable)}>
      <body className="font-body antialiased bg-grid-pattern">
        <FirebaseClientProvider>
          <CharacterProvider>
            {children}
          </CharacterProvider>
        </FirebaseClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
